version: "3"
services:
  user-service:
    build:
      context: ./user_service
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"

  post-service:
    build:
      context: ./post_service
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - user-service

  comment-service:
    build:
      context: ./comment_service
      dockerfile: ./Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - user-service
      - post-service
