version: "3"
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8001:8001"

  post-service:
    build:
      context: .
      dockerfile: Dockerfile.post
    ports:
      - "8002:8002"
    depends_on:
      - user-service

  comment-service:
    build:
      context: .
      dockerfile: Dockerfile.comment
    ports:
      - "8003:8003"
    depends_on:
      - user-service
      - post-service